if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin()
Plug 'Valloric/YouCompleteMe'
Plug 'altercation/vim-colors-solarized'
Plug 'editorconfig/editorconfig-vim'
Plug 'junegunn/fzf'
Plug 'pearofducks/ansible-vim'
Plug 'rdnetto/YCM-Generator'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-syntastic/syntastic'
Plug 'luisjure/csound-vim'
Plug 'elixir-editors/vim-elixir'
call plug#end()

" colors and syntax
" set termguicolors
syntax enable
set background=dark
colorscheme solarized

" use the solarized theme for airline
let g:airline#extensions#tabline#enabled=1
let g:airline_theme='solarized'
let g:airline_solarized_bg='dark'
let g:airline_powerline_fonts=1

" spaces & tabs
set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
set modelines=3
set modeline
filetype indent on
filetype plugin on
set autoindent
set smartindent
set cindent
autocmd FileType javascript,yaml,yaml.ansible setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab

" UI configuration
set cursorline
set wildmenu
set showmatch
set number

" show tabs and trailing spaces
set list
" in case you want to have EOL displayed, use the following line
" set listchars=eol:⏎,tab:␉·,trail:␠,nbsp:⎵
set listchars=tab:␉·,trail:␠,nbsp:⎵

" syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_java_checkers = []

" YouCompleteMe settings
let g:ycm_java_binary_path = "/usr/lib64/openjdk-11/bin/java"

" backups
set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*
set writebackup
